function [fitresult, gof] = createFit_min_poly5(nstruct)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 07-Mar-2025 15:34:54

x = nstruct.LambdaRes;
y = nstruct.local_min_valores;

[xData, yData] = prepareCurveData( x, y );

ordemPoly = 'poly5';
erroPoly = 0;
fcPoly = 0;

while fcPoly ~= 1

    switch erroPoly
        case 1
            ordemPoly = 'poly4';
        case 2
            ordemPoly = 'poly3';
        case 3
            ordemPoly = 'poly2';
    end

    try
        ft = fittype( ordemPoly );

        [fitresult, gof] = fit( xData, yData, ft, 'Normalize', 'on' );

        fcPoly = 1;
    catch    
        erroPoly = erroPoly + 1;    
        if erroPoly > 6
            erroCusto = 1e100;
            return;
        end
    end
end