function struct_out = montar_struct (struct_I)

Lambda = get_or_default(struct_I, 'Lambda', 0);
a2T = get_or_default(struct_I, 'a2T', 0);
local_min_indices = get_or_default(struct_I, 'local_min_indices', 0);
local_max_indices = get_or_default(struct_I, 'local_max_indices', 0);
local_min_valores = get_or_default(struct_I, 'local_min_valores', 0);
local_max_valores = get_or_default(struct_I, 'local_max_valores', 0);
range_idx = get_or_default(struct_I, 'range_idx', 0);

FE = get_or_default(struct_I, 'FE', 0);
LambdaRes = get_or_default(struct_I, 'LambdaRes', 0);
FSR = get_or_default(struct_I, 'FSR', 0);
FWHM = get_or_default(struct_I, 'FWHM', 0);
F = get_or_default(struct_I, 'F', 0);
Q = get_or_default(struct_I, 'Q', 0);
Tf = get_or_default(struct_I, 'Tf', 0);
dtLambda1 = get_or_default(struct_I, 'dtLambda1', 0);
dtLambda2 = get_or_default(struct_I, 'dtLambda2', 0);
Ng1v = get_or_default(struct_I, 'Ng1v', 0);
FWHM_pot = get_or_default(struct_I, 'FWHM_pot', 0);

t = get_or_default(struct_I, 't', 0);

struct_out = struct( ...
        't', t, ...
        'FE', FE, ...
        'LambdaRes', LambdaRes, ...
        'FSR', FSR, ...
        'FWHM', FWHM, ...
        'F', F, ...
        'Q', Q, ...
        'Tf', Tf, ...
        'dtLambda1', dtLambda1, ...
        'dtLambda2', dtLambda2, ...
        'Ng1v', Ng1v, ...
        'FWHM_pot', FWHM_pot, ...
        'Lambda', Lambda, ...
        'a2T', a2T, ...
        'local_min_indices', local_min_indices, ...
        'local_max_indices', local_max_indices, ...
        'local_min_valores', local_min_valores, ...
        'local_max_valores', local_max_valores, ...
        'range_idx', range_idx ...
    );
end

function value = get_or_default(structure, field, default_value)
    if isfield(structure, field) && ~isempty(structure.(field))
        value = structure.(field);
    else
        value = default_value;
    end
end



